---
title: "class06"
author: "Anusorn Mudla"
date: "4/19/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview 
Today we will focus on **functions** but we will start with **file reading**
```{r}
old.par <- par()
par(mfcol=c(1,3))
plot(1:10,type = "b",col = rainbow(10))
barplot(1:10,col = rainbow(10))
hist(rnorm(1000),bin=50)
#reset the parameter
par(old.par)

```

```{r}
data1 <- read.table("test1.txt",header = TRUE,sep = ",")
```

```{r}
data2 <- read.table("test2.txt",header = TRUE,sep = "$")
```

```{r}
data3 <- read.table("test3.txt")
```

```{r}
read.csv("https://bioboot.github.io/bggn213_S19/class-material/test1.txt")
```


```{r}
# function to read file
readfile <- function(file,header,sep) {
  read.table(file,header = header,sep = sep)
}
```

```{r}
add <- function(x,y=1) {
  # adding x to y
  x+y
}
add(4)
add(c(1,2,5))
add(c(1,2,5),3)
```

```{r}
rescale <- function(x) {
    rng <- range(x,na.rm = TRUE)
    (x - rng[1])/(rng[2]-rng[1])
}
```

```{r}
rescale2 <- function(x,na.rm = TRUE) {
    rng <- range(x,na.rm=na.rm)
    (x - rng[1])/(rng[2]-rng[1])
}
```

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
   if(na.rm) {
     rng <-range(x, na.rm=na.rm)
   } else {
     rng <-range(x)
   }
   print("Hello")
   answer <- (x - rng[1]) / (rng[2] - rng[1])
   print("is it me you are looking for?")
   if(plot) {
      plot(answer, typ="b", lwd=4)
   }
   print("I can see it in ...")
   return(answer)
}
```

```{r}
proteins <- c("1AKE","4AKE")
for (index in proteins) {
  print(index)
}

for (index in seq_along(proteins)) {
  print(index)
}
```

