CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Ferret_STAT1               KRNLQDNFQEDPVQMSMIICNCLKEERRILENAQRFNQAQSGSIQSTVMLDKQKELDSKV
African_bush_elephant      KRNLQDNFQEDPILMSMIICNCLKEERKILENAQRFNQAQSGNIQSTVMLDKQKELDSKV
Human_STAT1                KRNLQDNFQEDPIQMSMIIYSCLKEERKILENAQRFNQAQSGNIQSTVMLDKQKELDSKV
Bovine                     KRNLQDNFQEDPIQMSMIICNCLKEERKILDHAQRISQAQSGNIQSTVMLDKQKELDSKV
Finless_porpoise           KRNLQDNFQEDPIQMSMIICNCLKEERKILENAQRFNQAQAGNIQSTVMLDKQQELDSRV
Beluga_whale               KRNLQDNFQEDPIQMSMIICNCLKEERKILENAQRFNQAQAGNIQSTVMLDKQQELDSRV
Horse                      KRNLQDNFQEDPIQMSMIICSCLKEERKILENAQRFNQAQSGNIQSTVMLDKQKELDSRV
Sea_otter                  KRNLQDNFQEDPIQMSMIICNCLKEERRILENAQRFNQAQSGSIQNTVMLDKQKELDSKV
Cat                        KRNLQDNFQEDPIQMSMIIYNCLKEERKILENAQRFNQAQSGNIQSTVMLDKQKELDSKV
Polar_bear                 KRNLQDNFQEDPIQMSMIICNCLKEERKILENAQRFNQAQSGNIQSTVMLDKQKELDSKV
                           ************: ***** .******.**::***:.***:*.**.*******:****.*

Ferret_STAT1               RNVKDKVMCIEHEIKTLEDLQDEYDFKCKTLQNREHETNGVAKNDQKQEQLLIQKMYLML
African_bush_elephant      RNVKDKVMCIEHEIKTLEDLQDEYDFKCKTLQNREHETSGAAKNEQKEEQMLLQKMYLML
Human_STAT1                RNVKDKVMCIEHEIKSLEDLQDEYDFKCKTLQNREHETNGVAKSDQKQEQLLLKKMYLML
Bovine                     RNVKDKVMSIEHEIKTLEDLQDEYDFKCKTLQNREHETNGVAKNDQKQEQLLLQKMYLML
Finless_porpoise           RNVKDKVMCIEHEIKTLEDLQDEYDFKCKTLQNREHETNGVAKNDQKQEQMLLQKMYLML
Beluga_whale               RNVKDKVMCIEHEIKTLEDLQDEYDFKCKTLQNREHETNGVAKNDQKQEQMLLQKMYLML
Horse                      RNVKDKVMCIEQEIKTLEDLQDEYDFKCKTSQNREHEANGVAKNDQKQEQMLLQKMYLML
Sea_otter                  RNVKDKVMCIEHEIKTLEDLQDEYDFKCKTLQNREHETNGVAKNDQKQEQLLIQKMYLML
Cat                        RNVKDKVMCIEHEIKTLEDLQDEYDFKCKTLQNREHETNGVAKNDQKQEQMLIKKMYLML
Polar_bear                 RNVKDKVMCIEHEIKTLEDLQDEYDFKCKTLQNREHEANGVAKNDQKQEQMLIQKMYLML
                           ********.**:***:************** ******:.*.**.:**:**:*::******

Ferret_STAT1               DNKRKEVVLKIIELLNVTELTQKALINDELVEWKQRQQSACIGGPPNACLDQLQNWFTIV
African_bush_elephant      DNKRKEVVHKIIELLNVTELTQNALINDELVEWKRRQQSACIGGPPNACLDQLQNWFTIV
Human_STAT1                DNKRKEVVHKIIELLNVTELTQNALINDELVEWKRRQQSACIGGPPNACLDQLQNWFTIV
Bovine                     DNKRKEVVLKIIELLNATELTQKALINDELVEWKRRQQSACIGGPPNACLDQLQNWFTIV
Finless_porpoise           DNKRKEVVHKIIELLNVTELTQKALINDELVEWKRRQQSACIGGPPNACLDQLQNWFTIV
Beluga_whale               DNKRKEVVHKIIELLNATELTQKALINDELVEWKRRQQSACIGGPPNACLDQLQNWFTIV
Horse                      DNKRKEVVHKIIELLNVTELTQKALINDELVEWKRRQQSACIGGPPNACLDQLQNWFTIV
Sea_otter                  DNKRKEVVLKIIELLNVTELTQKALINDELVEWKQRQQSACIGGPPNACLDQLQNWFTIV
Cat                        DSKRKEVVHKIIELLNITELTQKALINDELVEWKQRQQSACIGGPPNACLDQLQNWFTIV
Polar_bear                 DNKRKEVVHKIIELLNVTELTQKALINDELVEWKQRQQSACIGGPPNACLDQLQNWFTIV
                           *.****** ******* *****:***********.*************************

Ferret_STAT1               AESLQQVRQQLKKLEELEQKYTYEHDPITKNKQGLWDRTFSLFQQLIQSSFVVERQPCMP
African_bush_elephant      AESLQQARQQLKKLEELEQKYTYEHDPITKNKQVLWDRTFTLFQQLIQSSFVVERQPCMP
Human_STAT1                AESLQQVRQQLKKLEELEQKYTYEHDPITKNKQVLWDRTFSLFQQLIQSSFVVERQPCMP
Bovine                     AESLQQVRQQLKKLEELEQKYTYEHDPITKNKQALWDRTFSLFQQLIQSSFVVERQPCMP
Finless_porpoise           AESLQQVRQQLKKLEELEQKYTYEHDPITKNKQALWDRTFSLFQQLIQSSFVVERQPCMP
Beluga_whale               AESLQQVRQQLKKLEELEQKYTYEHDPITKNKQALWDRTFSLFQQLIQSSFVVERQPCMP
Horse                      AESLQQVRQQLKKLEELEQKYTYEHDPITKNKQGLWDRTFSLFQQLIQNSFVVERQPCMP
Sea_otter                  AESLQQVRQQLKKLEELEQKYTYEHDPITKNKQGLWDRTFSLFQQLIQSSFVVERQPCMP
Cat                        AESLQQVRQQLKKLEELEQKYTYEHDPITKNKQGLWDRTFNLFQQLIQSSFVVERQPCMP
Polar_bear                 AESLQQVRQQLKKLEELEQKYTYEHDPITKNKQGLWDRTFSLFQQLIQSSFVVERQPCMP
                           ******.************************** ******.*******.***********

Ferret_STAT1               THPQRPLVLKTGVQFTVKLRLLVKLQELNYNLKVKVLFDKDVNERNTVKGFRKFNILGTH
African_bush_elephant      THPQRPLVLKTGVQFTVKLRLLVKLQELNYNLTVKVLFDKDVNERNTVKGFRKFNILGTH
Human_STAT1                THPQRPLVLKTGVQFTVKLRLLVKLQELNYNLKVKVLFDKDVNERNTVKGFRKFNILGTH
Bovine                     THPQRPLVLKTGVQFTVKLRLLVKLQELNYNLKVKVLFDKDVNERNTVKGFRKFNILGTH
Finless_porpoise           THPQRPLVLKTGVQFTVKLRLLVKLQELNYNLKVKVLFDKDVNERNTVKGFRKFNILGTH
Beluga_whale               THPQRPLVLKTGVQFTVKLRLLVKLQELNYNLKVKVLFDKDVNERNTVKGFRKFNILGTH
Horse                      THPQRPLVLKTGVQFTVKLRLLVKLQELNYNLKVKVLFDKDVNERNTVKGFRKFNILGTH
Sea_otter                  THPQRPLVLKTGVQFTVKLRLLVKLQELNYNLKVKVLFDKDVNERNTVKGFRKFNILGTH
Cat                        THPQRPLVLKTGVQFTVKLRLLVKLQELNYNLKVKVLFDKDVNERNTVKGFRKFNILGTH
Polar_bear                 THPQRPLVLKTGVQFTVKLRLLVKLQELNYNLKVKVLFDKDVNERNTVKGFRKFNILGTH
                           ********************************.***************************

Ferret_STAT1               TKVMNMEESTNGSLAAEFRHLQLKEQKNAGTRTNEGPLIVTEELSLLSFETT-C-SSLVW
African_bush_elephant      KKVMNMEESTNGSLAAEFRHLQLKEQKNAGTRTNEGPLIVTEELHSFSFETQLCQPGLVI
Human_STAT1                TKVMNMEESTNGSLAAEFRHLQLKEQKNAGTRTNEGPLIVTEELHSLSFETQLCQPGLVI
Bovine                     TKVMNMEESTNGSLAAEFRHLQLKEQKNAGARTNEGPLIVTEELHSLSFETQLCQPGLVI
Finless_porpoise           TKVMNMEESTNGSLAAEFRHLQLKEQKNAGARTNEGPLIVTEELHSLSFETQLCQPGLVI
Beluga_whale               TKVMNMEESTNGSLAAEFRHLQLKEQKNAGARTNEGPLIVTEELHSLSFETQLCQPGLVI
Horse                      TKVMNMEESTNGSLAAEFRHLQLKEQKNAGTRTNEGPLIVTEELHSLSFETQLCQPGLVI
Sea_otter                  TKVMNMEESTNGSLAAEFRHLQLKEQKNAGTRTNEGPLIVTEELHSLSFETQLCQPGLVI
Cat                        TKVMNMEESTNGSLAAEFRHLQLKEQKNAGTRTNEGPLIVTEELHSLSFETQLCQPGLVI
Polar_bear                 TKVMNMEESTNGSLAAEFRHLQLKEQKNAGTRTNEGPLIVTEELHSLSFETQLCQPGLVI
                           .*****************************:*************  :****  * ..** 

Ferret_STAT1               SL-TSERPLGPFGDLQGRPLPRGWASILVETIVGTNP-EIVLLFNPPGDEGSALGET-SW
African_bush_elephant      DLETTSLPVVVISNVS--QLPSGWASILWYNMLVAEPRNLSFFLNPPCAQWAQLSEVLSW
Human_STAT1                DLETTSLPVVVISNVS--QLPSGWASILWYNMLVAEPRNLSFFLTPPCARWAQLSEVLSW
Bovine                     DLETTSLPVVVISNVS--QLPSGWASILWYNMLVAEPRNLSFFLNPPCARWSQLSEVLSW
Finless_porpoise           DLETASLPIVVISNVS--QLPSGWASILWYNMLVAEPRNLSFFLNPPCARWSQLSEVLSW
Beluga_whale               DLETASLPIVVISNVS--QLPSGWASILWYNMLVAEPRNLSFFLNPPCARWSQLSEVLSW
Horse                      DLETTSLPVVVISNVS--QLPSGWASILWYNMLVAEPRNLSFFLNPPCARWSQLSEVLSW
Sea_otter                  DLETTSLPIVVISNVS--QLPSGWASILWYNMLVTEPRNLSFFLNPPCARWSQLSEVLSW
Cat                        DLETTSLPIVVISNVS--QLPSGWASILWYNMLVTEPRNLSFFLNPPCARWSQLSEVLSW
Polar_bear                 DLETTSLPVVVISNVS--QLPSGWASILWYNMLVTEPRNLSFFLNPPCARWSQLSEVLSW
                           .* *:. *:  :.::.   ** ******  .:: ::* :: :::.**    : *.*. **

Ferret_STAT1               SFSSSHKR
African_bush_elephant      QFSSVTKR
Human_STAT1                QFSSVTKR
Bovine                     QFSSVTKR
Finless_porpoise           QFSSVTKR
Beluga_whale               QFSSVTKR
Horse                      QFSSVTKR
Sea_otter                  QFSSVTKR
Cat                        QFSSVTKR
Polar_bear                 QFSSVTKR
                           .***  **
